// integrations RENDER-CATALOG-SPEC §12 -- the render catalog's documents (test/canary/catalog-*.json)
// and manifest (test/catalog/manifest.json). Both are generated by integrations'
// scripts/build-render-catalog.ts, which holds the one shape rule (S1); the fork never computes a
// shape. This suite asserts what the fork can see on its own:
//
//   - every catalog-*.json is in the manifest and every manifest sheet has its file;
//   - each compiles through the BUILT bundle under the canary context, to at most 80,000 bytes (U10),
//     and the file's sha256 is the manifest's (a hand edit fails here: never edit a catalog-*.json);
//   - with the bundle the manifest was generated with, each sheet compiles to the bytes recorded;
//   - I23: every control of every sidebar panel is named in the manifest's axis table, and the table
//     names no control the panels lack. A new editor control fails this suite until the generator's
//     table names it (and the catalog is regenerated). A new value-dependent branch in
//     postProcess.ts is NOT caught here (runbook hazard: the generator's table is maintained by hand).
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { loadUmd, DEFAULT_UMD } = require('./_umd.cjs');
const { CANARY_DIR } = require('./build-canary.cjs');

const CATALOG_DIR = path.join(__dirname, 'catalog');
const MANIFEST = path.join(CATALOG_DIR, 'manifest.json');
const PANELS = path.join(__dirname, '..', 'src', 'App', 'InspectorDrawer', 'ConfigurationPanel', 'input-panels');
const HARD_BYTES = 80000;

let failed = 0;
function check(name, ok, detail) { if (!ok) failed++; console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${!ok && detail ? '  [' + String(detail).slice(0, 400) + ']' : ''}`); }
const sha256 = (s) => crypto.createHash('sha256').update(s).digest('hex');

// I23: the controls a panel file declares -- every `label="…"`, every MultiStylePropertyPanel
// `names` entry as `style.<name>`, and every `<…Input` element that carries no label (its own name).
function panelControls(source) {
  const out = new Set();
  for (const m of source.matchAll(/\slabel="([^"]+)"/g)) out.add(m[1]);
  // Only the array entries count (TextSidebarPanel picks one of two arrays by a `=== 'bold'` test).
  for (const m of source.matchAll(/names=\{([\s\S]*?)\}\s*\n/g)) for (const a of m[1].matchAll(/\[([^\]]*)\]/g)) for (const n of a[1].matchAll(/'([A-Za-z]+)'/g)) out.add(`style.${n[1]}`);
  for (const m of source.matchAll(/<([A-Z]\w*Input)\b/g)) {
    const rest = source.slice(m.index + m[0].length);
    const end = rest.search(/\n\s*<[A-Za-z/]/);
    const tag = end < 0 ? rest : rest.slice(0, end);
    if (!/\slabel=/.test(tag)) out.add(m[1]);
  }
  return out;
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
const { context, refs } = JSON.parse(fs.readFileSync(path.join(CANARY_DIR, '_context.json'), 'utf8'));
check('the manifest records the bundle and the context it was generated with', /^[0-9a-f]{64}$/.test(manifest.bundleSha256)
  && JSON.stringify(manifest.context) === JSON.stringify(context));

const files = fs.readdirSync(CANARY_DIR).filter((f) => /^catalog-.*\.json$/.test(f)).map((f) => f.slice(0, -5)).sort();
const listed = manifest.sheets.map((s) => s.stem).sort();
check('every catalog-*.json is a manifest sheet and every sheet has its file', JSON.stringify(files) === JSON.stringify(listed), `${files} vs ${listed}`);
check('the catalog holds at least one sheet', files.length > 0);

const umdSha = sha256(fs.readFileSync(DEFAULT_UMD));
const sameBundle = umdSha === manifest.bundleSha256;
const { dom, EB } = loadUmd();
try {
  for (const s of manifest.sheets) {
    const file = path.join(CANARY_DIR, `${s.stem}.json`);
    if (!fs.existsSync(file)) continue;
    const text = fs.readFileSync(file, 'utf8');
    check(`${s.stem}: the file's sha256 is the manifest's (generated, never hand-edited)`, sha256(text) === s.sha256);
    const html = EB.compileDocument(JSON.parse(text), context, refs);
    const bytes = Buffer.byteLength(html, 'utf8');
    check(`${s.stem}: compiles`, typeof html === 'string' && html.length > 0);
    check(`${s.stem}: at most ${HARD_BYTES} compiled bytes (${bytes})`, bytes <= HARD_BYTES);
    if (sameBundle) check(`${s.stem}: compiles to the manifest's ${s.bytes} bytes under the bundle it was generated with`, bytes === s.bytes, bytes);
    check(`${s.stem}: its last row is the END row`, JSON.parse(text)[JSON.parse(text).root.data.childrenIds.slice(-1)[0]]?.data?.props?.text === `END ${s.stem}`);
    check(`${s.stem}: lists its units`, Array.isArray(s.units) && s.units.length > 0 && s.units.every((u) => typeof u.key === 'string' && typeof u.row === 'string'));
  }
  if (!sameBundle) console.log(`NOTE  the built bundle (${umdSha.slice(0, 12)}) is not the one the manifest was generated with (${manifest.bundleSha256.slice(0, 12)}): byte equality not checked — regenerate the catalog`);
} finally {
  dom.window.close();
}

// I23.
const table = new Map();
for (const c of manifest.axisTable) {
  if (!table.has(c.panel)) table.set(c.panel, new Set());
  table.get(c.panel).add(c.control);
}
check('every axis-table entry has a class', manifest.axisTable.every((c) => ['axis', 'inert', 'fixed', 'excluded'].includes(c.class)));
for (const f of fs.readdirSync(PANELS).filter((x) => x.endsWith('SidebarPanel.tsx')).sort()) {
  const panel = f.replace(/\.tsx$/, '');
  const controls = panelControls(fs.readFileSync(path.join(PANELS, f), 'utf8'));
  const named = table.get(panel) || new Set();
  const missing = [...controls].filter((c) => !named.has(c));
  check(`I23: ${panel}: every control is named in the manifest's axis table`, missing.length === 0, missing.join(', '));
  const stale = [...named].filter((c) => !controls.has(c));
  check(`I23: ${panel}: the axis table names no control the panel lacks`, stale.length === 0, stale.join(', '));
}

// I23 must fail on a new control: a panel with one control more is caught.
{
  const probe = panelControls('<TextInput\n        label="A new control"\n      />\n<ColumnWidthsInput\n  defaultValue={x}\n  onChange={(v) => f(v)}\n/>\n<MultiStylePropertyPanel\n  names={[\'padding\', \'newStyle\']}\n');
  check('I23 self-test: a labelled input, an unlabelled input and a style name are each read', probe.has('A new control') && probe.has('ColumnWidthsInput') && probe.has('style.newStyle'), [...probe].join(', '));
}

console.log(failed ? `\n${failed} FAILURES` : '\nALL PASS');
process.exit(failed ? 1 : 0);
